--- #YAML:1.0
name:               Test
version:            1.25_02
abstract:           provides a simple framework for writing test scripts
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:     0
    Test::Harness:  1.1601
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.49_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
